services:
  ram-api-gateway:
    container_name: ram-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - ram-shared-network
    env_file:
      - .env

networks:
  ram-shared-network:
    external: true
